workspace:
  base: /workspace
  path: src/github.com/bitlogic/devops-demo
pipeline:
  publish:
    image: plugins/docker
    repo: bitlogicos/demo-vote
    context: vote/
    dockerfile: vote/Dockerfile
    tag:
    - latest
    - "1.0.${DRONE_BUILD_NUMBER}"


